name: Terraform CD

on:
  push:
    branches:
      - dev
      - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false
      
jobs:
  apply:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_env: ${{ github.ref_name }}
      TF_VAR_project_name: pdfforge
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -migrate-state -backend-config "key=pdfforge/${{ github.event.pull_request.base.ref }}/terraform.tfstate"
      
      - name: Plan Terraform
        run: terraform plan
      
      - name: Apply Terraform
        run: terraform apply --auto-approve
