name: CI workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  terraform-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        env:i
          AWS_ACCESS_KEY_ID: anaccesskey
          AWS_SECRET_ACCESS_KEY: asecretkey
          TF_VAR_env: dev
          TF_VAR_project_name: devops-term-2
        run: terraform plan
